name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run RestAssured Tests and Generate Allure Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 with Maven
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Verify Maven Installation
        run: |
          mvn -version
          which mvn

      - name: Cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}

      - name: Run RestAssured Test Suite
        run: |
          chmod +x mvnw
          chmod +x runSuite.sh
          ./runSuite.sh

      - name: Generate Allure Report
        run: |
          chmod +x openAllure.sh
          ./openAllure.sh &
          sleep 10
          pkill -f allure

      - name: Upload Allure Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: target/site/allure-maven-plugin


      - name: Display Allure Report Info
        run: echo "Allure Report is available in the CI/CD artifacts."
